### ISSUE TITLE
photometry related: the `name` in `LIGHT_SOURCE_MAP` is experiment specific

### ISSUE THREAD

**Issue by grg2rsr** [int-brain-lab/ibllib#886]
The [light source map](https://github.com/int-brain-lab/ibllib/blob/e110a244db60f67cd47d1e01c10a8faec132885c/ibllib/io/extractors/fibrephotometry.py#L43)  as it is hard coded right now contains experiment specific information

```
LIGHT_SOURCE_MAP = {
    'color': ['None', 'Violet', 'Blue', 'Green'],
    'wavelength': [0, 415, 470, 560],
    'name': ['None', 'Isosbestic', 'GCaMP', 'RCaMP'],
}
```
both `color` and `wavelength` are neurophotometrics FP3002 specific, but `name` is not. For example, the green blue excitation band at 470 nm might well be used to image dLight, the 560 channel might be used for tdTomato.

This could probably be moved to the experiment description file as such:

```
"""
neurophotometrics:
    fibers:
    - roi: G0
        location: VTA
    - roi: G1
        location: DR
    channel_names: Isosbestic, GCaMP, RCaMP
    collection: raw_photometry_data
    sync_label: bnc1out
    sync_channel: 1
    datetime: 2024-09-19T14:13:18.749259
sync:
    bpod
"""
```
it might be worth thinking about having `channel_names` a property of each fiber, as it could be possible that someone tries to image different sensors at different locations
